spring: 
  profiles: test
  jpa:
    show-sql: true
  datasource: 
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo-security
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Chongqing
    
server: 
  port: 8083
  context-path: /PassionTest